test-cases/spec_error.erl:-1: foo: Type spec unmatch;
  success type: fun((111) -> 'ok')
  type spec   : fun((number()) -> 'true' | 'false')
test-cases/spec_error.erl:-1: int1: Type spec unmatch;
  success type: fun(() -> 'ok')
  type spec   : fun(() -> number())
test-cases/spec_error.erl:-1: int2: Type spec unmatch;
  success type: fun(() -> 'ok')
  type spec   : fun(() -> number())
test-cases/spec_error.erl:-1: int3: Type spec unmatch;
  success type: fun(() -> 'ok')
  type spec   : fun(() -> number())
test-cases/spec_error.erl:-1: int4: Type spec unmatch;
  success type: fun(() -> 'ok')
  type spec   : fun(() -> number())
test-cases/spec_error.erl:-1: bar: Type spec unmatch;
  success type: fun((number(), number()) -> 'ok')
  type spec   : fun(('true' | 'false', number()) -> 'ok')
